version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.7.4-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_HIPE_COMPILE=1
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379